<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/chosen.min.css')
                ->appendStylesheet($this->basePath() . '/css/chosen-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/blueimp-gallery.min.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload-ui.css')
                ->appendStylesheet($this->basePath() . '/css/typeahead.js-bootstrap.css')
                ?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Product'); ?></h3>
</div>
<div class="panel-body">
<?php
$form = $this->productForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/product/add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?=$this->form()->openTag($form) ?>
<? $product = $form->get('product-form');?>
<?=$this->formHidden($product->get('id')); ?>

<? $shop = $product->get('shop'); ?>
<div class="form-group <?php if($this->formElementErrors($shop)) 
echo "has-error" ?>">
<?php echo $this->formLabel($shop); ?>
<div class="col-sm-7">
<?php echo $this->formElement($shop) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($shop); ?>
</div>
</div>

<? $type = $product->get('type'); ?>
<div class="form-group <?php if($this->formElementErrors($type)) 
echo "has-error" ?>">
<?php echo $this->formLabel($type); ?>
<div class="col-sm-7">
<?php echo $this->formElement($type) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($type); ?>
</div>
</div>

<? $name = $product->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="col-sm-7">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? $description = $product->get('description'); ?>
<div class="form-group <?php if($this->formElementErrors($description)) 
echo "has-error" ?>">
<?php echo $this->formLabel($description); ?>
<div class="col-sm-7">
<?php echo $this->formElement($description) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($description); ?>
</div>
</div>

<? $price = $product->get('price'); ?>
<div class="form-group <?php if($this->formElementErrors($price)) 
echo "has-error" ?>">
<?php echo $this->formLabel($price); ?>
<div class="col-sm-7">
<div class="input-group">  
  <?php echo $this->formElement($price) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($price); ?>
    <span class="input-group-addon">Ariary</span>
</div>

</div>
</div>

<? $measurement = $product->get('measurement'); ?>
<div class="form-group <?php if($this->formElementErrors($measurement)) 
echo "has-error" ?>">
<?php echo $this->formLabel($measurement); ?>
<div class="col-sm-7">
<div class="input-group"> 
<?php echo $this->formElement($measurement) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($measurement); ?>
    <span class="input-group-addon input-grp-qty">Pi&egrave;ce</span>
</div>
</div>
</div>
<!--
<? //$attributesCollection = $product->get('attributes');?>
<div id="attributes-group">
	<? foreach ($attributesCollection as $c):?>	
	<div class="attributes-element">
		<? //echo $this->formHidden($c->get('product'));?>
		<div class="form-group">
			<?=$this->formLabel($c->get('attribute')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('attribute')); ?>			
			</div>
		</div>
		<div class="form-group <?php if($this->formElementErrors($c->get('value'))) 
echo "has-error" ?>">
			<?=$this->formLabel($c->get('value')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('value')); ?>
			<?=$this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($c->get('value')); ?>
			</div>
		</div>
	</div>
	<? endforeach;?>
</div>

<div class="form-group">
	<span id="tplAttribute" data-template="<?=htmlspecialchars('<div class="attributes-element"><input type="hidden" value="" name="product-form[attributes][__placeholder__][id]"><div class="form-group"><label for="product-form[attributes][__placeholder__][type]" class="col-sm-3 control-label">').
	$this->translate('Attribute type').htmlspecialchars('</label><div class="col-sm-7"><select class="form-control" name="product-form[attributes][__placeholder__][type]"><option value="1">').
	$this->translate('mobile').htmlspecialchars('</option><option value="2">').$this->translate('mail').htmlspecialchars('</option><option value="3">').
	$this->translate('address').htmlspecialchars('</option></select></div></div><div class="form-group"><label for="product-form[attributes][__placeholder__][value]" class="col-sm-3 control-label">').
	$this->translate('Attribute value').htmlspecialchars('</label><div class="col-sm-7"><input type="text" value="" class="form-control" name="product-form[attributes][__placeholder__][value]"></div></div></div>') ?>"></span>
	<div class="col-sm-4 col-sm-offset-3"></div>
</div>

-->
<? echo $this->formHidden($product->get('deleted'));?>
<div id="attributes-group"></div>

<? echo $this->formHidden($form->get('csrf'));?>
<div class="listFileId"></div>
<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
	<i class="glyphicon glyphicon-picture"></i>
	<span><?=$this->translate('Add image'); ?></span>
</button>
</div>
</div>
<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>

</div>
</div>
</div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog wide-modal">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload image</h4>
      </div>
      <div class="modal-body">
      <? 
      	$form = $this->fileForm;
		$form->prepare();
		$form->setAttribute('class', 'form-inline');
		echo $this->form()->openTag($form);
		$elem = $form->get('files');
		?>
		<div class="row fileupload-buttonbar">
			<div class="container button-bar">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
		                <!-- The fileinput-button span is used to style the file input field as button -->
		                <span class="btn btn-success fileinput-button">
		                    <i class="glyphicon glyphicon-plus"></i>
		                    <span><?=$this->translate('Add files...'); ?></span>
		                    <?php echo $this->formFile($elem); ?>
		                </span>
		                <button type="submit" class="btn btn-primary start">
		                    <i class="glyphicon glyphicon-upload"></i>
		                    <span><?=$this->translate('Start upload'); ?></span>
		                </button>
		                <button type="reset" class="btn btn-warning cancel">
		                    <i class="glyphicon glyphicon-ban-circle"></i>
		                    <span><?=$this->translate('Cancel upload'); ?></span>
		                </button>
		                <button type="button" class="btn btn-danger delete">
		                    <i class="glyphicon glyphicon-trash"></i>
		                    <span><?=$this->translate('Delete'); ?></span>
		                </button>
		                <input type="checkbox" class="toggle">
		                
		                <!-- The global file processing state -->
		                <span class="fileupload-process"></span>
		            </div>
		            <!-- The global progress state -->
		            <div class="col-md-9 col-md-offset-1 fileupload-progress fade">
		                <!-- The global progress bar -->
		                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
		                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
		                </div>
		                <!-- The extended global progress state -->
		<!--                <div class="progress-extended">&nbsp;</div>-->
		            </div>
				</div>
			</div>
            
<!--            <div class="col-md-11">-->
<!--            <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>-->
<!--            </div>-->
			<div class="clearfix visible-md"></div>
            <div class="container media-content">
            	<div class="row">
            	<div class="col-md-8 image-preview-container">
            		<div class="container ">
            			<div class="row files"></div>		
            		</div>
            	</div>
				<div class="col-md-4 image-edit-container">
            		<div class="container ">
            			<div class="row"><div class="col-md-12"><div class="image-detail-container"></div></div></div>		
            		</div>
            	</div>
            	</div>
			</div>
			<div class="shadow-modal-footer"></div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('Close'); ?></button>
        <button type="button" id="save-images" class="btn btn-primary" disabled="disabled"><?=$this->translate('Insert into post'); ?></button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">

{% for (var i=0, file; file=o.files[i]; i++) { %}
<div class="col-md-3 template-upload fade">
{% if (i) { %}
	<span class="preview">
       	{% if (file.thumbnailUrl) { %}
           	<a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
    	{% } %}
		<span class="my-progress">
			<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
		</span>
	</span>
{% } else { %}
	<strong class="error text-danger"></strong>
	<button class="btn btn-warning cancel">
    	<i class="glyphicon glyphicon-ban-circle"></i>
        <span>Cancel</span>
	</button>
{% } %}
</div>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
<div class="col-md-3 col-sm-3 col-xs-4 template-download fade">
	<span class="preview">
		{% if (file.thumbnailUrl) { %}
			<img src="{%=file.thumbnailUrl%}" class="img-thumbnail img-thumbnail-preview">
			<span class="my-zoom-icon">
				<a href='#' data-toggle="tooltip" title="Deselect" class="deselect my-tooltip"><span class="glyphicon glyphicon-minus"></span></a> 
				<a href="{%=file.url%}" download="{%=file.name%}" data-gallery  data-toggle="tooltip" title="Zoom" class="my-tooltip"><span class="glyphicon glyphicon-zoom-in"></span></a> 
				<a href="#" class="delete my-tooltip"  data-toggle="tooltip" title="Delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}><span class="glyphicon glyphicon-remove"></span></a>
			</span>
			<input type="hidden" class="fileId" value="{%=file.id%}"/>
		{% } %}
		{% if (file.error) { %}
			<span class="my-progress">			
        		<div><span class="label label-danger">Error</span> {%=file.error%}</div>            
			</span>
		{% } %}
		<input type="checkbox" name="delete" value="1" class="toggle hidden">
	</span>	
</div>
{% } %}
</script>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/typeahead.min.js')
			->appendFile($this->basePath() . '/js/chosen.jquery.min.js')
			->appendFile($this->basePath() . '/js/main.js')
			->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js')
            ->appendFile($this->basePath() . '/js/tmpl.min.js')
            ->appendFile($this->basePath() . '/js/load-image.min.js')
            ->appendFile($this->basePath() . '/js/canvas-to-blob.min.js')
            ->appendFile($this->basePath() . '/js/jquery.blueimp-gallery.min.js')
            ->appendFile($this->basePath() . '/js/jquery.iframe-transport.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-process.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-video.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-ui.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-validate.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-image.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-audio.js');?>
<script type="text/javascript">
$(function() {
	$(".chosen-select.shop-select").chosen({ 
		width: '100%',
		disable_search_threshold: 10,
	}).change(function(event){
		if(event.target == this){
		}
	});

	$('#save-images').click(function(e) {
		$('.fileId').each(function() {
			if ($(this).hasClass('file-selected')) {				
	   			$('.listFileId').append('<input type="hidden" name="file-id[]" class="file-id" value="'+$(this).val()+'">');
			}   		
		});
		$('#myModal').modal('hide');		
		return false;
	});


	/* ADDING MORE ATTRIBUTE */
	var tplAttribute = $('#tplAttribute');
	var tplAttributeManager = tplAttribute.parent();

	var addAttribute = function () {
	    var attributesGroup = $('#attributes-group');
	    var attributesCount = attributesGroup.find('.attributes-element').length;
	    attributesGroup.append(tplAttribute.data('template').replace(/__placeholder__/g, attributesCount));
	}

	var btnAttributes = $('<button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i><?=$this->translate('Add attribute'); ?></button>')
	    .button({
	        icons: {
	            primary: 'ui-icon-circle-plus'
	        }
	    }).on('click', function (e) {
	        e.preventDefault();
	        $('.removeElement').html('');
	        addAttribute();
	        //addRemoveButton('#attributes');
	    });

	tplAttributeManager.find('div').append(btnAttributes);	

	$(".chosen-select.product-type-select").on('liszt:ready', function(e, chosen) {
		var idType = e.currentTarget.value;
		$.ajax({
			url: "list-attribute?productType="+idType,
    		type: "POST",
    		cache: false,
    		dataType: "json",
    		beforeSend: function() {					
    		},
            success: function(data) {
	            var unit = data.unit;
	            $('.input-grp-qty').html(unit);
	            var attributes = data.attribute;
            	$('#attributes-group').html('');
	            for (i = 0; i < attributes.length; i++) {				            
		            var id = attributes[i].id;
		            var name = attributes[i].name;
		            addAttrElem(i, id, name);
	            }
	        }
		});
	}).chosen({ 
		width: '100%',
		disable_search_threshold: 10,
	}).change(function(event, params){
		if(event.target == this){
			var idType = params.selected;
			$.ajax({
				url: "list-attribute?productType="+idType,
	    		type: "POST",
	    		cache: false,
	    		dataType: "json",
	    		beforeSend: function() {					
	    		},
	    		success: function(data) {
		            var unit = data.unit;
		            $('.input-grp-qty').html(unit);
		            var attributes = data.attribute;
	            	$('#attributes-group').html('');
		            for (i = 0; i < attributes.length; i++) {				            
			            var id = attributes[i].id;
			            var name = attributes[i].name;
			            addAttrElem(i, id, name);
		            }
		        }
			});
		}
	});

	var addAttrElem = function(index, id, label) {
		var attributeElem = '<div class="attributes-element">';
		attributeElem += '<input type="hidden" name="attributes['+index+'][id]" value="'+id+'">';
		attributeElem += '<div class="form-group">';
		attributeElem += '<label class="col-sm-3 control-label" for="attributes['+index+'][value]">'+label+'</label>';
		attributeElem += '<div class="col-sm-7">';
		attributeElem += '<input class="form-control" type="text" name="attributes['+index+'][value]">';
		attributeElem += '</div></div></div>';
		$('#attributes-group').append(attributeElem);
	}
	
});
</script>

<!-- The blueimp Gallery widget -->
        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter="">
		    <div class="slides"></div>
		    <h3 class="title"></h3>
		    <a class="prev">‹</a>
		    <a class="next">›</a>
		    <a class="close">×</a>
		    <a class="play-pause"></a>
		    <ol class="indicator"></ol>
		</div>