<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/chosen.min.css')
                ->appendStylesheet($this->basePath() . '/css/chosen-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')                
                ->appendStylesheet($this->basePath() . '/css/typeahead.js-bootstrap.css')
                ?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Shop'); ?></h3>
</div>
<div class="panel-body">
<?php
$form = $this->shopForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/shop_admin/shop_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>
<? $shop = $form->get('shop-form'); ?>
<? echo $this->formHidden($shop->get('id'));?>

<? $categories = $shop->get('categories'); ?>
<? $value_options = $categories->getValueOptions();?>
<? if (count($value_options) > 0):?>
<div class="form-group <?php if($this->formElementErrors($categories)) 
echo "has-error" ?>">
<?php echo $this->formLabel($categories); ?>
<div class="col-sm-7">
<?php echo $this->formElement($categories) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($categories); 
	?>
</div>
</div>
<? endif;?>
<div id="categories-group">
<!--	 More categories to add here -->
</div>

<!--<? $categoriesCollection = $shop->get('new-categories');?>
<div id="categories-group">
	<? foreach ($categoriesCollection as $c):?>
	<div class="categories-element">
		<? echo $this->formHidden($c->get('id'));?>
		<div class="form-group">
			<?=$this->formLabel($c->get('name')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('name')); ?>
			<?=$this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($c->get('name')); ?>
			</div>
		</div>		
	</div>
	<? endforeach;?>
</div>

--><div class="form-group">
	<span id="tplCategory" data-template="<?=htmlspecialchars('<div class="categories-element"><input type="hidden" value="" name="shop-form[new-categories][__placeholder__][id]"><div class="form-group"><label for="shop-form[new-categories][__placeholder__][name]" class="col-sm-3 control-label">').
	$this->translate('Category name').htmlspecialchars('</label><div class="col-sm-7"><input type="text" value="" class="form-control" name="shop-form[new-categories][__placeholder__][name]"></div></div></div>') ?>"></span>
	<div class="col-sm-4 col-sm-offset-3"></div>
</div>

<? $name = $shop->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="col-sm-7">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? $description = $shop->get('description'); ?>
<div class="form-group <?php if($this->formElementErrors($description)) 
echo "has-error" ?>">
<?php echo $this->formLabel($description); ?>
<div class="col-sm-7">
<?php echo $this->formElement($description) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($description); ?>
</div>
</div>

<? $owner = $shop->get('owner'); ?>
<div class="form-group <?php if($this->formElementErrors($owner)) 
echo "has-error" ?>">
<?php echo $this->formLabel($owner); ?>
<div class="col-sm-7">
<?php echo $this->formElement($owner) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($owner); ?>
</div>
</div>

<? $city = $shop->get('idCity'); ?>
<div class="form-group <?php if($this->formElementErrors($city)) 
echo "has-error" ?>">
<?php echo $this->formLabel($city); ?>
<div class="col-sm-7">
<?php echo $this->formElement($city) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($city); ?>
</div>
</div>
<? echo $this->formHidden($shop->get('cities'));?>

<? $contactsCollection = $shop->get('contacts');?>
<div id="contacts-group">
	<? foreach ($contactsCollection as $c):?>
	<div class="contacts-element">
		<? echo $this->formHidden($c->get('id'));?>
		<div class="form-group">
			<?=$this->formLabel($c->get('type')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('type')); ?>			
			</div>
		</div>
		<div class="form-group <?php if($this->formElementErrors($c->get('value'))) 
echo "has-error" ?>">
			<?=$this->formLabel($c->get('value')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('value')); ?>
			<?=$this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($c->get('value')); ?>
			</div>
		</div>
	</div>
	<? endforeach;?>
</div>

<div class="form-group">
	<span id="tplContact" data-template="<?=htmlspecialchars('<div class="contacts-element"><input type="hidden" value="" name="shop-form[contacts][__placeholder__][id]"><div class="form-group"><label for="shop-form[contacts][__placeholder__][type]" class="col-sm-3 control-label">').
	$this->translate('Contact type').htmlspecialchars('</label><div class="col-sm-7"><select class="form-control new-contact-chosen" name="shop-form[contacts][__placeholder__][type]"><option value="1">').
	$this->translate('mobile').htmlspecialchars('</option><option value="2">').$this->translate('mail').htmlspecialchars('</option><option value="3">').
	$this->translate('address').htmlspecialchars('</option></select></div></div><div class="form-group"><label for="shop-form[contacts][__placeholder__][value]" class="col-sm-3 control-label">').
	$this->translate('Contact value').htmlspecialchars('</label><div class="col-sm-7"><input type="text" value="" class="form-control" name="shop-form[contacts][__placeholder__][value]"></div></div></div>') ?>"></span>
	<div class="col-sm-4 col-sm-offset-3"></div>
</div>
<? echo $this->formHidden($shop->get('deleted'));?>
<? echo $this->formHidden($form->get('csrf'));?>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>

</div>
</div>
</div>
</div>   

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/typeahead.min.js')
			->appendFile($this->basePath() . '/js/chosen.jquery.min.js')
			->appendFile($this->basePath() . '/js/select2.min.js')
			//->appendFile($this->basePath() . '/js/main.js')
			->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js');?>
<script type="text/javascript">
$(function() {
	$(".chosen-select").select2({
		minimumResultsForSearch: 10,
	});

	$("#id_city").select2({
		placeholder: "Search for a city",
	    minimumInputLength: 3,
	    ajax: { // instead of writing the function to execute the request we use Select2's convenient helper
	        url: "city",
	        dataType: 'json',
	        quietMillis: 100,
	        data: function (term, page) {
	            return {
	                q: term, // search term
	                page_limit: 10,
	                page: page, // page number
	            };
	        },
	        results: function (data, page) { // parse the results into the format expected by Select2.
	            // since we are using custom formatting functions we do not need to alter remote JSON data
	            var more = (page * 10) < data.total; // whether or not there are more results available
	            return {results: data.results, more: more};
	        }
//	        results: data
	    },
	    formatSelection: format,
	    formatResult: format
	});
	$('#id_city').change(function(e) {
		$('#city').val($(this).val());
	});
	function format(item) { return item.text; };

	/* ADDING MORE CATEGORY */
	var tplCategory = $('#tplCategory');
	var tplCategoryManager = tplCategory.parent();

	var addCategory = function () {
	    var categoriesGroup = $('#categories-group');
	    var categoriesCount = categoriesGroup.find('.categories-element').length;
	    categoriesGroup.append(tplCategory.data('template').replace(/__placeholder__/g, categoriesCount));
	}

	var btnCategories = $('<button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i><?=$this->translate('Add category'); ?></button>')
	    .button({
	        icons: {
	            primary: 'ui-icon-circle-plus'
	        }
	    }).on('click', function (e) {
	        e.preventDefault();
	        $('.removeElement').html('');
	        addCategory();
	        //addRemoveButton('#categories');
	    });

	tplCategoryManager.find('div').append(btnCategories);
	
	/* ADDING MORE CONTACT */
	var tplContact = $('#tplContact');
	var tplContactManager = tplContact.parent();

	var addContact = function () {
	    var contactsGroup = $('#contacts-group');
	    var contactsCount = contactsGroup.find('.contacts-element').length;
	    contactsGroup.append(tplContact.data('template').replace(/__placeholder__/g, contactsCount));
	}

	var btnContacts = $('<button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i><?=$this->translate('Add contact'); ?></button>')
	    .button({
	        icons: {
	            primary: 'ui-icon-circle-plus'
	        }
	    }).on('click', function (e) {
	        e.preventDefault();
	        $('.removeElement').html('');
	        addContact();
	        $(".new-contact-chosen").chosen({ 
	    		width: '100%',
	    		placeholder_text_multiple: 'Choose a category...', 
	    		disable_search_threshold: 10,
	    	})
	        //addRemoveButton('#contacts');
	    });

	tplContactManager.find('div').append(btnContacts);
});
</script>