<?php echo $this->headLink()                
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')      
                ->appendStylesheet($this->basePath() . '/css/typeahead.js-bootstrap.css')
                ?>
<div class="row">
<div class="col-md-7 col-md-offset-2">
<div class="panel panel-default">
<div class="panel-body">
<?php
$form = $this->shopForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/shop_admin/shop_edit', array('lang' => $this->lang, 'id' => $this->shopId)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<? $shop = $form->get('shop-form'); ?>
<? echo $this->formHidden($shop->get('id'));?>

<? $categories = $shop->get('categories'); ?>
<? $value_options = $categories->getValueOptions();?>
<? if (count($value_options) > 0):?>
<div class="form-group <?php if($this->formElementErrors($categories)) 
echo "has-error" ?>">
<?php echo $this->formLabel($categories); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($categories) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($categories); 
	?>
</div>
</div>
<? endif;?>
<!-- <div id="categories-group">-->
<!--	 More categories to add here -->
<!--</div>-->

<div class="form-group">
	<span id="tplCategory" data-template="<?=htmlspecialchars('<div class="categories-element"><input type="hidden" value="" name="shop-form[new-categories][__placeholder__][id]"><div class="form-group"><label for="shop-form[new-categories][__placeholder__][name]" class="col-sm-3 control-label">').
	$this->translate('Category name').htmlspecialchars('</label><div class="gdn_input_margin"><input type="text" value="" class="form-control" name="shop-form[new-categories][__placeholder__][name]"></div></div></div>') ?>"></span>
	<div class="col-sm-4 col-sm-offset-3"></div>
</div>

<? $name = $shop->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? $description = $shop->get('description'); ?>
<div class="form-group <?php if($this->formElementErrors($description)) 
echo "has-error" ?>">
<?php echo $this->formLabel($description); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($description) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($description); ?>
</div>
</div>

<? $owner = $shop->get('owner'); ?>
<div class="form-group <?php if($this->formElementErrors($owner)) 
echo "has-error" ?>">
<?php echo $this->formLabel($owner); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($owner) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($owner); ?>
</div>
</div>

<? $citiesCollection = $shop->get('cities');?>
<div id="cities-group">
	<? foreach ($citiesCollection as $c):?>
	<div class="cities-element">
		<div class="form-group" <?php if($this->formElementErrors($c->get('cityAccented'))) 
echo "has-error" ?>">
			<?=$this->formLabel($c->get('cityAccented')); ?>
			<div class="gdn_input_margin">
			<?=$this->formElement($c->get('cityAccented')); ?>
			<?=$this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($c->get('cityAccented')); ?>			
			</div>
		</div>		
	</div>
	<? endforeach;?>
</div>

<? $contactsCollection = $shop->get('contacts');?>

<? foreach ($contactsCollection as $c):
	$contactId = $c->get('id');
	$contactType = $c->get('type');
	$contactValue = $c->get('value');
	//var_dump($contactType);
?>
<div class="gdn_input_margin contact_group">
	<div class="form-group <?php if($this->formElementErrors($contactValue)) 
		echo "has-error" ?>">
		<?=$this->formHidden($contactId); ?>
		<?=$this->formElement($contactType); ?>
		<div class="input-group">
	  		<div class="input-group-btn">
				<button type="button" class="btn btn-default btn_lg gdn_btn dropdown-toggle" data-toggle="dropdown"><span class="contact_selected" data-type="1"><i class='fa fa-mobile-phone fa-2x'></i></span> <span class="caret"></span></button>
				<ul class="dropdown-menu contact_choice">
		  			<li><a href="#" data-value="1" ><i class="fa fa-mobile-phone fa-2x"></i> <?=$this->translate('Mobile') ?></a></li>
		  			<li><a href="#" data-value="2" ><strong>@</strong> <?=$this->translate('Email')?></a></li>
		  			<li><a href="#" data-value="3" ><i class="fa fa-home"></i> <?=$this->translate('Adress')?></a></li>
		  			<li class="divider"></li>
		  			<li><a href="#" class="add_contact"><i class="fa fa-plus"></i> <?=$this->translate('Contact') ?></a></li>
				</ul>
	  		</div><!-- /.input-group-btn -->
	  		<?php echo $this->formElement($contactValue) ?>			
		</div><!-- /input-group -->
		<?php  echo $this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($contactValue); ?>
	</div><!-- /.form-group -->
</div><!-- /.contact_group -->
<? endforeach;?>



<span id="tplContact" data-template='
<?=htmlspecialchars('<div class="gdn_input_margin contact_group"><div class="form-group"><input type="hidden" value="" name="shop-form[contacts][__placeholder__][id]">
<input type="hidden" name="shop-form[contacts][__placeholder__][type]" class="contact_type"><div class="input-group">
<div class="input-group-btn"><button data-toggle="dropdown" class="btn btn-default btn_lg gdn_btn dropdown-toggle" type="button"><span class="contact_selected" data-type="1"><i class="fa fa-mobile-phone fa-2x"></i></span> <span class="caret"></span></button>
<ul class="dropdown-menu contact_choice">
<li><a data-value="1" href="#"><i class="fa fa-mobile-phone fa-2x"></i> ')
 . $this->translate('Mobile') .
htmlspecialchars('</a></li><li><a data-value="2" href="#"><strong>@</strong> ')
 . $this->translate('Email') .
htmlspecialchars('</a></li><li><a data-value="3" href="#"><i class="fa fa-home"></i> ')
 . $this->translate('Adress') .
htmlspecialchars('</a></li><li class="divider"></li><li><a class="remove_contact" href="#"><i class="fa fa-minus"></i> ')
 . $this->translate('Contact') . 
htmlspecialchars('</a></li></ul></div><input type="text" value="" placeholder="')
 . $this->translate('Contact') .
htmlspecialchars('" class="gdn_text" name="shop-form[contacts][__placeholder__][value]"></div></div></div>'); ?>
'></span>


<? echo $this->formHidden($shop->get('deleted'));?>
<? echo $this->formHidden($form->get('csrf'));?>

<div class="fd_upload pull-left">
<button class="btn btn-info"><?=$this->translate('Change cover'); ?></button>
</div>
<div class="fd_action pull-right">
<? echo $this->formElement($form->get('submit'));?>
</div>

<?php echo $this->form()->closeTag() ?>

</div>
</div>
</div>
</div>   

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')
			->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js');?>
<script type="text/javascript">
var category_placeholder = "<?=$this->translate('Categories'); ?>";
var owner_placeholder = "<?=$this->translate('Owner'); ?>";
var city_placeholder = "<?=$this->translate('City'); ?>";
$(function() {
	$(".category-select").select2({
		placeholder: category_placeholder,
		minimumResultsForSearch: 10,
	});
	$(".owner-select").select2({
		placeholder: owner_placeholder,
		minimumResultsForSearch: 10,
	});	
	$(".chosen-select").select2({
		minimumResultsForSearch: 10,
	});
	$('.contact_group').each(function() {
		var that = this;
		var choice = $(that).find('.contact_type').val();
		var contact_selected = $(that).find('.contact_selected');  
		var contact_type = $(that).find('.contact_type');
		choice = parseInt(choice);
		switch (choice) {
			case 1: // Mobile 
				$(contact_selected).html("<i class='fa fa-mobile-phone fa-2x'></i>");
				break;
			case 2: // Email				
				$(contact_selected).html("<strong>@</strong>");
				break;
			case 3: // Address
				$(contact_selected).html("<i class='fa fa-home fa-lg'></i>");
				break;
			default:
				$(contact_selected).html("<i class='fa fa-mobile-phone fa-2x'></i>");
				break;
		}
	});
	$(document).on("click", ".add_contact", function() {
		var contactsCount = $('#edit-shop-form').find('.contact_group').length;
		var template = $("#tplContact").data('template').replace(/__placeholder__/g, contactsCount);	
		$(template).insertAfter( '.contact_group:last' );		
		$( '.contact_group:last' ).find('.contact_type').val(1);	
		return false;
	});

	//$('.contact_type').val(1);

	$(document).on("click", ".contact_choice a", function() {
		var choice = $(this).data('value');
		var contact_selected = $(this).parents('.input-group-btn').find('.contact_selected');  
		var contact_type = $(this).parents('.contact_group').find('.contact_type');
		//$(contact_selected).data("type", 45);
		switch (choice) {
			case 1: // Mobile 
				$(contact_selected).html("<i class='fa fa-mobile-phone fa-2x'></i>");
				break;
			case 2: // Email
				$(contact_selected).html("<strong>@</strong>");
				break;
			case 3: // Address
				$(contact_selected).html("<i class='fa fa-home fa-lg'></i>");
				break;
		}
		if (!$(this).hasClass('add_contact') && !$(this).hasClass('remove_contact')) {	
			//console.log('add_contact');		
			$(contact_type).val(choice);
		}
		$(this).parents('.input-group-btn').removeClass('open');
		return false;
	});

	$(document).on("click", ".remove_contact", function() {
		$( '.contact_group:last' ).remove();
		//msnry.layout();
		return false;
	});
});
</script>