
<div class="row">

<? $shops = $this->shops;?>
<? $count = 0;?>
<? foreach ($shops as $shop):?>
<? 
	$shopId = $shop->getId();
	$shopIdent = $shop->getIdent();
	$name = $shop->getName();
	$description = $shop->getDescription();
	$categories = $shop->getCategories();
	$categoryToDisplay = '';
	foreach ($categories as $category):
		$categoryToDisplay .= '<a class="btn btn-danger btn-xs" href="'.$this->url('shop', array('categoryIdent' => $category->getIdent()), array(), true).'">' . $category->getName() . '</a>' . ' ';
	endforeach;
	$categoryToDisplay = rtrim($categoryToDisplay, ' ');
?>
<? $count++;?>
<div class="col-md-4 col-sm-6">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title"><?=$name; ?>
			<a class="btn btn-primary pull-right btn-xs" href="<?=$this->url('detail-shop', array('shopIdent' => $shopIdent)) ?>"><?=$this->translate('More'); ?> <i class="glyphicon glyphicon-chevron-right"></i></a></h3>
		</div>
		<div class="panel-body">
			<p><?=$description; ?></p>
			
		</div>
		<div class="panel-footer">			
			<?=$categoryToDisplay; ?>
			
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<? if ($count % 3 == 0):?>
<div class="clearfix visible-md"></div>
<? elseif ($count % 2 == 0):?>
<div class="clearfix visible-sm"></div>
<? endif;?>
<? endforeach;?>
</div>