<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status === true):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<?php echo $this->translate('Password changed successfully.');?>
</div>
<? elseif ($this->status === false): ?>
<div class="alert alert-dismissable alert-danger">
<button data-dismiss="alert" class="close">×</button>
<?php echo $this->translate('Unable to update your password. Please try again.'); ?>
</div>
<? endif;?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<? if($this->formElementErrors($form->get('identity'))): ?>
<div class="alert alert-danger alert-dismissable">
<button data-dismiss="alert" class="close">×</button>
    	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div>')
                ->setMessageSeparatorString('</div><div>')
                ->setMessageCloseString('</div>')
                ->render($form->get('identity')); ?>
</div>
<? endif;?>
<?php echo $this->formInput($form->get('identity')); ?>

<div class="form-group <?php if($this->formElementErrors($form->get('credential'))) 
echo "has-error" ?>">
<?php echo $this->formLabel($form->get('credential')); ?>
<div class="col-sm-7">
<?php echo $this->formElement($form->get('credential')) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($form->get('credential')); 
	?>
</div>
</div>

<div class="form-group <?php if($this->formElementErrors($form->get('newCredential'))) 
echo "has-error" ?>">
<?php echo $this->formLabel($form->get('newCredential')); ?>
<div class="col-sm-7">
<?php echo $this->formElement($form->get('newCredential')) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($form->get('newCredential')); 
	?>
</div>
</div>

<div class="form-group <?php if($this->formElementErrors($form->get('newCredentialVerify'))) 
echo "has-error" ?>">
<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
<div class="col-sm-7">
<?php echo $this->formElement($form->get('newCredentialVerify')) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($form->get('newCredentialVerify')); 
	?>
</div>
</div>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-4">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>



<?php echo $this->form()->closeTag(); ?>
</div>
</div>
</div>
</div>