<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/datepicker3.css');?>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Profile'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Your profile is updated.'); ?> 
</div>
<? endif;?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    print "</div></div></div></div>";
    return;
}
$form = $this->profileForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/profile'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>
	<?php foreach ($form as $element): ?>
		<div class="form-group <?php if($this->formElementErrors($element)) 
                                echo "has-error" ?>">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element); ?>
        <?php endif; ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="col-sm-4 col-sm-offset-4"><?php echo $this->formButton($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div class="col-sm-5"><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
        	<div class="col-sm-5">
        		<?php echo $this->formSelect($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
        	</div>
        <?php else: ?>
            <div class="col-sm-5">
            	<?php echo $this->formInput($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
            </div>
        <?php endif ?>
        </div>
	<?php endforeach; ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>
<?php $this->inlineScript()
	->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js')
	->appendFile($this->basePath() . '/js/select2.min.js');
?>
<script type="text/javascript">
$(function() {
	$(".datepicker").datepicker({
		//language: 'fr'
	});
	$(".chosen-select").select2({
		minimumResultsForSearch: 10,
	});
});
</script>