<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('godana')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top nav-gdn-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand gdn-brand" href="<?php echo $this->url('home') ?>">godana</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<? echo $this->home_active; ?>">
                        	<a href="<?php echo $this->url('home') ?>"><? echo $this->translate('Home');?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('bid', array('type' => null, 'categoryIdent' => null), array(), true) ?>"><? echo $this->translate('Bid');?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('shop', array('categoryIdent' => null), array(), true) ?>"><? echo $this->translate('Shops');?></a>
                        </li>
                        <li>
                            <a href="#"><? echo $this->translate('Groups');?></a>
                        </li>
                        <li>
                            <a href="#"><? echo $this->translate('Tools');?></a>
                        </li>
                        <li>
                            <a href="#"><? echo $this->translate('About');?></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                         <? if ($this->zfcUserIdentity()):?>
                            	<li class="dropdown">
	                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $this->zfcUserDisplayName() ?> <i class="caret"></i>
	
	                                </a>
	                                <ul class="dropdown-menu">
	                                    <li>
	                                        <a tabindex="-1" href="<?php echo $this->url('zfcuser/profile') ?>"><i class="fa fa-user"></i> <? echo $this->translate('Profile');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? 
	                                    $roles = $this->currentUserRole();
	                                    $isAdmin = false;	
	                                    foreach ($roles as $role) {
	                                    	if ($role->getRoleId() == 'admin') {
	                                    		$isAdmin = true;
	                                    		break;
	                                    	}
	                                    }                    
	                                    if ($isAdmin):?>
	                                    <li>
	                                        <a tabindex="-1" href="<?=$this->url('admin'); ?>"><i class="fa fa-gear"></i> <? echo $this->translate('Admin');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? endif;?>
	                                    <li>
	                                        <a tabindex="-1" href="<?php echo $this->url('zfcuser/logout') ?>"><i class="fa fa-power-off"></i> <?php echo $this->translate('Sign Out'); ?></a>
	                                    </li>
	                                </ul>
	                            </li>
                            <? else: ?>
                            	<li><a href="<?php echo $this->url('zfcuser/login') ?>"><? echo $this->translate('Login');?></a></li>
                            <? endif;?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; Fano Raiza <?=date('Y'); ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
