<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/blueimp-gallery.min.css');?>
<?  $this->plugin("currencyformat")->setCurrencyCode("MGA")->setLocale("fr_FR");?>
<? $this->headTitle($this->translate('Bid'));?>
<? if ($this->zfcUserIdentity()):?>
<div class="row">
<div class="col-md-4 col-md-offset-5 col-sm-6">
<a class="btn btn-success btn-lg" href="<?=$this->url('add-bid', array('lang' => $this->lang)) ?>"><?=$this->translate('Create bid') ?></a>
</div></div>
<hr/>
<? endif;?>
<div id="ctnr">
<? $bids = $this->paginator;?>
<? $count = 0;?>
<? foreach ($bids as $bid):?>
<? $postIdent = $bid->getPost()->getIdent();?>
<? $type = $bid->getType();?>
<? if ($type === 0) {
	$typeBid = 'offer';
} else if ($type === 1) {
	$typeBid = 'demand';
}?>
<? //$typeBid = $bid->getType() == 0 ? 'offer' : 'demand';?>
<? $count++;?>
<div class="item">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?=$this->truncateText(stripcslashes($bid->getPost()->getTitle()), 20); ?>
			<? if ($this->zfcUserIdentity()):?>
			<a class="btn btn-default pull-right btn-xs" href="<?=$this->url('detail-bid', array('lang' => $this->lang, 'type' => $typeBid, 'postIdent' => $postIdent)) ?>"><?=$this->translate('More'); ?> <i class="glyphicon glyphicon-chevron-right"></i></a>
			<? endif;?>
			</h3>
		</div>
		<div class="panel-body">
			<p><?=stripcslashes($bid->getPost()->getDetail()); ?></p>
			<? $files = $bid->getPost()->getFiles();?>
			<? $postId = $bid->getPost()->getId();?>
			<? if (isset($files) && count($files) > 0):?>
				<div class="row" id="<?=$bid->getPost()->getId(); ?>">
				<? foreach ($files as $file):?>					
					  <div class="col-xs-6 col-sm-5 col-md-5" >					  
					    <a href="<?=$file->getUrl(); ?>" class="img-thumbnail"  download="<?=$file->getName(); ?>" data-gallery="#blueimp-gallery-<?=$postId; ?>">
					      <img src="<?=$file->getThumbnailUrl(); ?>" class="img-responsive">
					    </a>
					  </div>						  									
				<? endforeach;?>
				</div>
			<? endif;?>
			<h4 class="bid-info"><a href="<?=$this->url('bid', array('lang' => $this->lang, 'type' => $typeBid)) ?>" class="btn btn-success btn-xs"><?=$this->translate(ucfirst($typeBid)) ?></a>&nbsp;<span class="label label-danger"><?=$this->currencyFormat($bid->getPrice()); ?></span>
			<? $categories = $bid->getPost()->getCategories();?>
			<? if (isset($categories) && count($categories) > 0):?>	
			<br>	
			<? foreach ($categories as $category):?>
				<? $categoryIdent = $category->getIdent();?>
				<a class="btn btn-primary btn-xs" href="<?=$this->url('bid', array('lang' => $this->lang, 'type' => $typeBid, 'categoryIdent' => $categoryIdent)) ?>"><?=$category->getName(); ?></a>
			<? endforeach;?>
			<? endif;?>			
			</h4>
		</div>		
	</div>
</div>
<!--<? if ($count % 3 == 0):?>
<div class="clearfix visible-md"></div>
<? elseif ($count % 2 == 0):?>
<div class="clearfix visible-sm"></div>
<? endif;?>
--><? endforeach;?>



</div>
<hr/>
<div class="container">
<div class="row">
<?=$this->paginationControl(
		$this->paginator,
 		'sliding',
 		array('partial/paginator.phtml', 'Godana'),
	 	array(
	 		'route' => 'bid',
	 		'typeBid' => $this->typeBid,
	 		'categoryIdent' => $this->categoryIdent,
	 		'lang' => $this->lang
	 	)
);
?>
</div>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
	<div class="slides"></div>
	<h3 class="title"></h3>
	<a class="prev">‹</a>
	<a class="next">›</a>
	<a class="close">×</a>
	<a class="play-pause"></a>
	<ol class="indicator"></ol>
</div>

<script type="text/javascript">
<!--
$(function() {
	var container = document.querySelector('#ctnr');
	var msnry = new Masonry( container, {
	  // options
	  columnWidth: 100,
	  itemSelector: '.item'
	});
});
//-->
</script>

<? $this->inlineScript()->appendFile($this->basePath() . '/js/jquery.blueimp-gallery.min.js')
->appendFile($this->basePath() . '/js/masonry.pkgd.min.js');?>
