<?php echo $this->translate('Demand'); ?>
<?php echo $this->translate('Offer'); ?>
<?php echo $this->translate('appliance'); ?>
<?php echo $this->translate('agriculture'); ?>
<?php echo $this->translate('housing'); ?>
<?php echo $this->translate('technology'); ?>
<?php echo $this->translate('transportation'); ?>
<?php echo $this->translate('mining'); ?>
<?php echo $this->translate('Type'); ?>
<?php echo $this->translate('Categories'); ?>
<?php echo $this->translate('Title'); ?>
<?php echo $this->translate('Content'); ?>
<?php echo $this->translate('Choose a category...'); ?>
<?php echo $this->translate('Contact type'); ?>
<?php echo $this->translate('Contact value'); ?>
<?php echo $this->translate('Add contact'); ?>
<?php echo $this->translate('City'); ?>
<?php echo $this->translate('Price'); ?>
<?php echo $this->translate('Add image'); ?>
<?php echo $this->translate('Add files...'); ?>
<?php echo $this->translate('Start upload'); ?>
<?php echo $this->translate('Cancel upload'); ?>
<?php echo $this->translate('Delete'); ?>
<?php echo $this->translate('Close'); ?>
<?php echo $this->translate('Save changes'); ?>
<?php echo $this->translate('mobile');?>
<?php echo $this->translate('mail');?>
